environment:
  base_url: http://localhost:8080/api

variables:
  username: un
  password: pw

requests:
  - name: login
    headers:
      Content-Type: application/json
    method: POST
    path: "/login"
    body: |
      {
        "username": "{{username}}",
        "password": "{{password}}"
      }
    extractors:
      - type: json
        selectors:
          id: result.id
          token: result.token
    assertions:
      - type: is_not_null
        variable: "{{id}}"
      - type: is_uuid
        variable: "{{id}}"
  
  - name: get
    method: GET
    path: "/get/{{id}}"
    headers:
      Authorisation: Bearer {{token}}